let solidColors = [
  {
    id: '1',
    Lid: '1',
    Oid: '92',
    swatchId: '100',
    color: 'FFFFFF',
    BLName: 'White',
    LName: 'White',
    OName: 'White',
    parts: '13740',
    inSets: '10286',
    type: '',
    colorTimeline: '1949- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '49',
    Lid: '103',
    Oid: '19',
    swatchId: '200',
    color: 'E8E8E8',
    BLName: 'Very Light Gray',
    LName: 'Light Grey',
    OName: 'Very Light Gray',
    parts: '21',
    inSets: '23',
    type: '',
    colorTimeline: '1997-2004',
    flourescence: '',
    similar: ['208'],
    note: '',
  },
  {
    id: '99',
    Lid: '208',
    Oid: '90',
    swatchId: '300',
    color: 'E4E8E8',
    BLName: 'Very Light Bluish Gray',
    LName: 'Light Stone Grey',
    OName: 'Light Stone Gray',
    parts: '53',
    inSets: '49',
    type: '',
    colorTimeline: '2004-2013',
    flourescence: '',
    similar: ['49'],
    note: '',
  },
  {
    id: '86',
    Lid: '194',
    Oid: '64',
    swatchId: '400',
    color: 'AFB5C7',
    BLName: 'Light Bluish Gray',
    LName: 'Medium Stone Grey',
    OName: 'Medium Stone Gray',
    parts: '4283',
    inSets: '6688',
    type: '',
    colorTimeline: '2003- ',
    flourescence: '',
    similar: ['2'],
    note: '',
  },
  {
    id: '9',
    Lid: '2',
    Oid: '66',
    swatchId: '500',
    color: '9C9C9C',
    BLName: 'Light Gray',
    LName: 'Grey',
    OName: 'Light Gray',
    parts: '1860',
    inSets: '3197',
    type: '',
    colorTimeline: '1954-2008',
    flourescence: '',
    similar: ['194'],
    note: '',
  },
  {
    id: '10',
    Lid: '27',
    Oid: '53',
    swatchId: '600',
    color: '6B5A5A',
    BLName: 'Dark Gray',
    LName: 'Dark Grey',
    OName: 'Dark Gray',
    parts: '1053',
    inSets: '1699',
    type: '',
    colorTimeline: '1961- ',
    flourescence: '',
    similar: ['199'],
    note: '',
  },
  {
    id: '85',
    Lid: '199',
    Oid: '50',
    swatchId: '700',
    color: '595D60',
    BLName: 'Dark Bluish Gray',
    LName: 'Dark Stone Grey',
    OName: 'Dark Stone Gray',
    parts: '3724',
    inSets: '6170',
    type: '',
    colorTimeline: '2003- ',
    flourescence: '',
    similar: ['27'],
    note: '',
  },
  {
    id: '11',
    Lid: '26',
    Oid: '38',
    swatchId: '800',
    color: '212121',
    BLName: 'Black',
    LName: 'Black',
    OName: 'Black',
    parts: '11229',
    inSets: '11984',
    type: '',
    colorTimeline: '1957- ',
    flourescence: 'No',
    similar: [],
    note: '',
  },
  {
    id: '59',
    Lid: '154',
    Oid: '56',
    swatchId: '900',
    color: '6A0E15',
    BLName: 'Dark Red',
    LName: 'Dark Red',
    OName: 'Dark Red',
    parts: '1566',
    inSets: '1722',
    type: '',
    colorTimeline: '1961- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '5',
    Lid: '21',
    Oid: '81',
    swatchId: '1000',
    color: 'B30006',
    BLName: 'Red',
    LName: 'Bright Red',
    OName: 'Red',
    parts: '7416',
    inSets: '10148',
    type: '',
    colorTimeline: '1949- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '167',
    Lid: '402',
    Oid: '241',
    swatchId: '1100',
    color: 'FF5500',
    BLName: 'Reddish Orange',
    LName: 'Reddish Orange',
    OName: 'Reddish Orange',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2024- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '231',
    Lid: '123',
    Oid: '158',
    swatchId: '1200',
    color: 'FF6326',
    BLName: 'Dark Salmon',
    LName: 'Bright Reddish Orange',
    OName: 'Reddish Orange',
    parts: '5',
    inSets: '4',
    type: '',
    colorTimeline: '2003-2003',
    flourescence: '',
    similar: ['12'],
    note: '',
  },
  {
    id: '25',
    Lid: '12',
    Oid: '84',
    swatchId: '1300',
    color: 'FF7D5D',
    BLName: 'Salmon',
    LName: 'Medium Red',
    OName: 'Salmon',
    parts: '85',
    inSets: '27',
    type: '',
    colorTimeline: '1997-1999',
    flourescence: '',
    similar: ['123'],
    note: '',
  },
  {
    id: '220',
    Lid: '353',
    Oid: '173',
    swatchId: '1350',
    color: 'FF8172',
    BLName: 'Coral',
    LName: 'Vibrant Coral',
    OName: 'Coral',
    parts: '165',
    inSets: '240',
    type: '',
    colorTimeline: '2019- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '26',
    Lid: '100',
    Oid: '5',
    swatchId: '1400',
    color: 'FCC7B7',
    BLName: 'Light Salmon',
    LName: 'Light Red',
    OName: 'Light Salmon',
    parts: '50',
    inSets: '21',
    type: '',
    colorTimeline: '1997-2002',
    flourescence: '',
    similar: ['17'],
    note: '',
  },
  {
    id: '58',
    Lid: '153',
    Oid: '87',
    swatchId: '1500',
    color: 'C58D80',
    BLName: 'Sand Red',
    LName: 'Sand Red',
    OName: 'Sand Red',
    parts: '39',
    inSets: '18',
    type: '',
    colorTimeline: '2001-2004',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '168',
    Lid: '423',
    Oid: '243',
    swatchId: '1550',
    color: '50372F',
    BLName: 'Umber',
    LName: 'Umber Brown',
    OName: 'Umber Brown',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2024- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '120',
    Lid: '308',
    Oid: '51',
    swatchId: '1600',
    color: '50372F',
    BLName: 'Dark Brown',
    LName: 'Dark Brown',
    OName: 'Dark Brown',
    parts: '699',
    inSets: '1552',
    type: '',
    colorTimeline: '2008- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '8',
    Lid: '217',
    Oid: '46',
    swatchId: '1700',
    color: '6B3F22',
    BLName: 'Brown',
    LName: 'Earth Orange',
    OName: 'Brown',
    parts: '581',
    inSets: '1089',
    type: '',
    colorTimeline: '1974-2006',
    flourescence: '',
    similar: ['192'],
    note: '',
  },
  {
    id: '91',
    Lid: '86',
    Oid: '52',
    swatchId: '1800',
    color: '99663E',
    BLName: 'Light Brown',
    LName: 'Brown',
    OName: 'Dark Flesh',
    parts: '40',
    inSets: '28',
    type: '',
    colorTimeline: '2002-2006',
    flourescence: '',
    similar: ['370'],
    note: '',
  },
  {
    id: '240',
    Lid: '370',
    Oid: '213',
    swatchId: '1900',
    color: 'A16C42',
    BLName: 'Medium Brown',
    LName: 'Medium Brown',
    OName: 'Medium Brown',
    parts: '6',
    inSets: '5',
    type: '',
    colorTimeline: '2022- ',
    flourescence: '',
    similar: ['86'],
    note: '',
  },
  {
    id: '88',
    Lid: '192',
    Oid: '82',
    swatchId: '2000',
    color: '82422A',
    BLName: 'Reddish Brown',
    LName: 'Reddish Brown',
    OName: 'Reddish Brown',
    parts: '1972',
    inSets: '4077',
    type: '',
    colorTimeline: '2003- ',
    flourescence: '',
    similar: ['217'],
    note: '',
  },
  {
    id: '106',
    Lid: '12',
    Oid: '23',
    swatchId: '2100',
    color: 'B3694E',
    BLName: 'Fabuland Brown',
    LName: 'Brick Red',
    OName: 'Fabuland Brown',
    parts: '7',
    inSets: '26',
    type: '',
    colorTimeline: '1979-1997',
    flourescence: '',
    similar: ['128'],
    note: '',
  },
  {
    id: '69',
    Lid: '138',
    Oid: '57',
    swatchId: '2200',
    color: 'B89869',
    BLName: 'Dark Tan',
    LName: 'Sand Yellow',
    OName: 'Dark Tan',
    parts: '1034',
    inSets: '2207',
    type: '',
    colorTimeline: '1961- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '241',
    Lid: '371',
    Oid: '217',
    swatchId: '2300',
    color: 'D9C594',
    BLName: 'Medium Tan',
    LName: 'Warm Tan',
    OName: 'Warm Tan',
    parts: '5',
    inSets: '3',
    type: '',
    colorTimeline: '2022- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '2',
    Lid: '19',
    Oid: '89',
    swatchId: '2400',
    color: 'EED9A4',
    BLName: 'Tan',
    LName: 'Brick Yellow',
    OName: 'Tan',
    parts: '2295',
    inSets: '4504',
    type: '',
    colorTimeline: '1958- ',
    flourescence: '',
    similar: ['224'],
    note: '',
  },
  {
    id: '169',
    Lid: '422',
    Oid: '245',
    swatchId: '2425',
    color: '82422A',
    BLName: 'Sienna',
    LName: 'Sienna Brown',
    OName: 'Sienna Brown',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2024- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '224',
    Oid: '',
    swatchId: '2450',
    color: 'F3C988',
    BLName: '',
    LName: 'Light Brick Yellow',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '2004-2006',
    flourescence: '',
    similar: ['19'],
    note: '',
  },
  {
    id: '90',
    Lid: '283',
    Oid: '65',
    swatchId: '2500',
    color: 'FECCB0',
    BLName: 'Light Nougat',
    LName: 'Light Nougat',
    OName: 'Light Flesh',
    parts: '1639',
    inSets: '1618',
    type: '',
    colorTimeline: '2004- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '28',
    Lid: '18',
    Oid: '6',
    swatchId: '2600',
    color: 'FFAF7D',
    BLName: 'Nougat',
    LName: 'Nougat',
    OName: 'Flesh',
    parts: '244',
    inSets: '280',
    type: '',
    colorTimeline: '1979- ',
    flourescence: '',
    similar: ['312'],
    note: '',
  },
  {
    id: '150',
    Lid: '312',
    Oid: '74',
    swatchId: '2700',
    color: 'E3A05B',
    BLName: 'Medium Nougat',
    LName: 'Medium Nougat',
    OName: 'Medium Dark Flesh',
    parts: '870',
    inSets: '1405',
    type: '',
    colorTimeline: '2010- ',
    flourescence: '',
    similar: ['18'],
    note: '',
  },
  {
    id: '225',
    Lid: '128',
    Oid: '160',
    swatchId: '2800',
    color: 'CE7942',
    BLName: 'Dark Nougat',
    LName: 'Dark Nougat',
    OName: 'Dark Nougat',
    parts: '3',
    inSets: '10',
    type: '',
    colorTimeline: '2001-2004',
    flourescence: '',
    similar: ['12'],
    note: '',
  },
  {
    id: '160',
    Lid: '19',
    Oid: '60',
    swatchId: '2900',
    color: 'EF9121',
    BLName: 'Fabuland Orange',
    LName: 'Light Brown',
    OName: 'Fauland Orange',
    parts: '2',
    inSets: '3',
    type: '',
    colorTimeline: '1983-1987',
    flourescence: '',
    similar: ['12'],
    note: '',
  },
  {
    id: '29',
    Lid: '12',
    Oid: '59',
    swatchId: '3000',
    color: 'E6881D',
    BLName: 'Earth Orange',
    LName: 'Light Orange Brown',
    OName: 'Earth Orange',
    parts: '37',
    inSets: '87',
    type: '',
    colorTimeline: '1982-2005',
    flourescence: '',
    similar: ['19'],
    note: '',
  },
  {
    id: '68',
    Lid: '38',
    Oid: '54',
    swatchId: '3100',
    color: 'B35408',
    BLName: 'Dark Orange',
    LName: 'Dark Orange',
    OName: 'Dark Orange',
    parts: '710',
    inSets: '1589',
    type: '',
    colorTimeline: '1985- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '27',
    Lid: '216',
    Oid: '83',
    swatchId: '3200',
    color: 'B24817',
    BLName: 'Rust',
    LName: 'Rust',
    OName: 'Rust',
    parts: '13',
    inSets: '20',
    type: '',
    colorTimeline: '1979-2005',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '165',
    Lid: '133',
    Oid: '',
    swatchId: '3300',
    color: 'FA5947',
    BLName: 'Neon Orange',
    LName: 'Neon Orange',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '1997-2001',
    flourescence: '',
    similar: [],
    note: 'Never released in bricks, only wristwatch links, see part bb1001',
  },
  {
    id: '4',
    Lid: '106',
    Oid: '80',
    swatchId: '3400',
    color: 'FF7E14',
    BLName: 'Orange',
    LName: 'Bright Orange',
    OName: 'Orange',
    parts: '1967',
    inSets: '3265',
    type: '',
    colorTimeline: '1993- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '31',
    Lid: '105',
    Oid: '7',
    swatchId: '3500',
    color: 'FFA531',
    BLName: 'Medium Orange',
    LName: 'Bright Yellowish Orange',
    OName: 'Medium Orange',
    parts: '130',
    inSets: '113',
    type: '',
    colorTimeline: '1950-2007',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '110',
    Lid: '191',
    Oid: '43',
    swatchId: '3600',
    color: 'FFC700',
    BLName: 'Bright Light Orange',
    LName: 'Flame Yellowish Orange',
    OName: 'Bright Light Orange',
    parts: '1063',
    inSets: '1544',
    type: '',
    colorTimeline: '2000- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '32',
    Lid: '121',
    Oid: '8',
    swatchId: '3700',
    color: 'FFBC36',
    BLName: 'Light Orange',
    LName: 'Medium Yellowish Orange',
    OName: 'Light Orange',
    parts: '18',
    inSets: '18',
    type: '',
    colorTimeline: '1998-2004',
    flourescence: '',
    similar: ['36', '125', '225'],
    note: '',
  },
  {
    id: '',
    Lid: '125',
    Oid: '',
    swatchId: '3725',
    color: 'F9A777',
    BLName: '',
    LName: 'Light Orange',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '2000-2003',
    flourescence: '',
    similar: ['225', '121', '36'],
    note: '',
  },
  {
    id: '',
    Lid: '225',
    Oid: '',
    swatchId: '3775',
    color: 'FAA964',
    BLName: '',
    LName: 'Warm Yellowish Orange',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '2004-2004',
    flourescence: '',
    similar: ['121', '125', '36'],
    note: '',
  },
  {
    id: '96',
    Lid: '36',
    Oid: '91',
    swatchId: '3800',
    color: 'FFDCA4',
    BLName: 'Very Light Orange',
    LName: 'Light Yellowish Orange',
    OName: 'Very Light Orange',
    parts: '10',
    inSets: '3',
    type: '',
    colorTimeline: '2000-2003',
    flourescence: '',
    similar: ['125', '225', '121'],
    note: '',
  },
  {
    id: '161',
    Lid: '180',
    Oid: '169',
    swatchId: '3900',
    color: 'DD982E',
    BLName: 'Dark Yellow',
    LName: 'Curry',
    OName: 'Curry',
    parts: '4',
    inSets: '4',
    type: '',
    colorTimeline: '2004-2005',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '3',
    Lid: '24',
    Oid: '93',
    swatchId: '4000',
    color: 'FFE001',
    BLName: 'Yellow',
    LName: 'Bright Yellow',
    OName: 'Yellow',
    parts: '6489',
    inSets: '9945',
    type: '',
    colorTimeline: '1949- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '190',
    Oid: '',
    swatchId: '4050',
    color: 'FFCF0B',
    BLName: '',
    LName: 'Fire Yellow',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '2003-2004',
    flourescence: '',
    similar: [],
    note: 'Clikits',
  },
  {
    id: '33',
    Lid: '24',
    Oid: '9',
    swatchId: '4100',
    color: 'FFE383',
    BLName: 'Light Yellow',
    LName: 'Light Yellow',
    OName: 'Light Yellow',
    parts: '94',
    inSets: '71',
    type: '',
    colorTimeline: '1994-2011',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '103',
    Lid: '226',
    Oid: '44',
    swatchId: '4200',
    color: 'FEED83',
    BLName: 'Bright Light Yellow',
    LName: 'Cool Yellow',
    OName: 'Bright Light Yellow',
    parts: '420',
    inSets: '762',
    type: '',
    colorTimeline: '2004- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '236',
    Lid: '368',
    Oid: '211',
    swatchId: '4300',
    color: 'FFFC00',
    BLName: 'Neon Yellow',
    LName: 'Vibrant Yellow',
    OName: 'Vibrant Yellow',
    parts: '65',
    inSets: '30',
    type: '',
    colorTimeline: '2022- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '166',
    Lid: '134',
    Oid: '',
    swatchId: '4400',
    color: 'DBF355',
    BLName: 'Neon Green',
    LName: 'Neon Green',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '1997-2001',
    flourescence: '',
    similar: [],
    note: 'Never released in bricks, only wristwatch links, see part bb1001',
  },
  {
    id: '35',
    Lid: '120',
    Oid: '67',
    swatchId: '4500',
    color: 'ECEEBD',
    BLName: 'Light Lime',
    LName: 'Light Yellowish Green',
    OName: 'Light Lime',
    parts: '20',
    inSets: '16',
    type: '',
    colorTimeline: '1992-2007',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '15',
    Oid: '',
    swatchId: '4550',
    color: 'FFF230',
    BLName: '',
    LName: 'Lemon',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '1992-1992',
    flourescence: '',
    similar: [],
    note: 'Lemon-Lime',
  },
  {
    id: '158',
    Lid: '326',
    Oid: '94',
    swatchId: '4600',
    color: 'E7F2A7',
    BLName: 'Yellowish Green',
    LName: 'Spring Yellowish Green',
    OName: 'Yellowish Green',
    parts: '184',
    inSets: '255',
    type: '',
    colorTimeline: '2012- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '76',
    Lid: '115',
    Oid: '77',
    swatchId: '4700',
    color: 'DFE000',
    BLName: 'Medium Lime',
    LName: 'Medium Yellowish Green',
    OName: 'Medium Lime',
    parts: '66',
    inSets: '40',
    type: '',
    colorTimeline: '1998-2005',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '248',
    Lid: '14',
    Oid: '237',
    swatchId: '4800',
    color: 'ADD237',
    BLName: 'Fabuland Lime',
    LName: 'Pastel Green',
    OName: 'Fabuland Lime',
    parts: '9',
    inSets: '5',
    type: '',
    colorTimeline: '1982-1986',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '34',
    Lid: '119',
    Oid: '70',
    swatchId: '4900',
    color: 'C4E000',
    BLName: 'Lime',
    LName: 'Bright Yellowish Green',
    OName: 'Lime',
    parts: '1641',
    inSets: '2418',
    type: '',
    colorTimeline: '1993- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '242',
    Lid: '144',
    Oid: '',
    swatchId: '5000',
    color: '76753F',
    BLName: 'Dark Olive Green',
    LName: 'Dark Army Green',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2000-2001',
    flourescence: '',
    similar: [],
    note: 'Never released in bricks, only wristwatch links, see part bb1007',
  },
  {
    id: '155',
    Lid: '330',
    Oid: '79',
    swatchId: '5100',
    color: 'ABA953',
    BLName: 'Olive Green',
    LName: 'Olive Green',
    OName: 'Olive Green',
    parts: '522',
    inSets: '447',
    type: '',
    colorTimeline: '2012- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '80',
    Lid: '141',
    Oid: '20',
    swatchId: '5200',
    color: '2E5543',
    BLName: 'Dark Green',
    LName: 'Earth Green',
    OName: 'Dark Green',
    parts: '862',
    inSets: '970',
    type: '',
    colorTimeline: '1961- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '6',
    Lid: '28',
    Oid: '61',
    swatchId: '5300',
    color: '00923D',
    BLName: 'Green',
    LName: 'Dark Green',
    OName: 'Green',
    parts: '1988',
    inSets: '5089',
    type: '',
    colorTimeline: '1949- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '36',
    Lid: '37',
    Oid: '41',
    swatchId: '5400',
    color: '10CB31',
    BLName: 'Bright Green',
    LName: 'Bright Green',
    OName: 'Bright Green',
    parts: '607',
    inSets: '1830',
    type: '',
    colorTimeline: '1950- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '37',
    Lid: '29',
    Oid: '10',
    swatchId: '5500',
    color: '91DF8C',
    BLName: 'Medium Green',
    LName: 'Medium Green',
    OName: 'Medium Green',
    parts: '122',
    inSets: '102',
    type: '',
    colorTimeline: '1950-2004',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '38',
    Lid: '6',
    Oid: '11',
    swatchId: '5600',
    color: 'D7EED1',
    BLName: 'Light Green',
    LName: 'Light Green',
    OName: 'Light Green',
    parts: '66',
    inSets: '60',
    type: '',
    colorTimeline: '1992-2005',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '210',
    Oid: '',
    swatchId: '5625',
    color: '468A5F',
    BLName: '',
    LName: 'Faded Green',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '2003-2003',
    flourescence: '',
    similar: [],
    note: 'Little Robots Baseplate',
  },
  {
    id: '',
    Lid: '233',
    Oid: '',
    swatchId: '5675',
    color: '60BA76',
    BLName: '',
    LName: 'Light Faded Green',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '2004-2004',
    flourescence: '',
    similar: [],
    note: 'Little Robots Cart',
  },
  {
    id: '48',
    Lid: '151',
    Oid: '18',
    swatchId: '5700',
    color: 'A2BFA3',
    BLName: 'Sand Green',
    LName: 'Sand Green',
    OName: 'Sand Green',
    parts: '596',
    inSets: '643',
    type: '',
    colorTimeline: '1964- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '39',
    Lid: '107',
    Oid: '58',
    swatchId: '5800',
    color: '00A29F',
    BLName: 'Dark Turquoise',
    LName: 'Bright Bluish Green',
    OName: 'Dark Turquoise',
    parts: '595',
    inSets: '656',
    type: '',
    colorTimeline: '1998- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '40',
    Lid: '116',
    Oid: '12',
    swatchId: '5900',
    color: '00C5BC',
    BLName: 'Light Turquoise',
    LName: 'Medium Bluish Green',
    OName: 'Light Turquoise',
    parts: '58',
    inSets: '40',
    type: '',
    colorTimeline: '1998-2004',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '41',
    Lid: '118',
    Oid: '13',
    swatchId: '6000',
    color: 'BCE5DC',
    BLName: 'Aqua',
    LName: 'Light Bluish Green',
    OName: 'Aqua',
    parts: '82',
    inSets: '60',
    type: '',
    colorTimeline: '1998-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '152',
    Lid: '323',
    Oid: '62',
    swatchId: '6100',
    color: 'CFEFEA',
    BLName: 'Light Aqua',
    LName: 'Aqua',
    OName: 'Light Aqua',
    parts: '430',
    inSets: '492',
    type: '',
    colorTimeline: '2011- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '63',
    Lid: '140',
    Oid: '48',
    swatchId: '6200',
    color: '243757',
    BLName: 'Dark Blue',
    LName: 'Earth Blue',
    OName: 'Dark Blue',
    parts: '2077',
    inSets: '1997',
    type: '',
    colorTimeline: '1961- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '7',
    Lid: '23',
    Oid: '39',
    swatchId: '6300',
    color: '0057A6',
    BLName: 'Blue',
    LName: 'Bright Blue',
    OName: 'Blue',
    parts: '3893',
    inSets: '8021',
    type: '',
    colorTimeline: '1950- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '153',
    Lid: '321',
    Oid: '47',
    swatchId: '6400',
    color: '009FE0',
    BLName: 'Dark Azure',
    LName: 'Dark Azur',
    OName: 'Dark Azure',
    parts: '660',
    inSets: '847',
    type: '',
    colorTimeline: '2000- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '247',
    Lid: '269',
    Oid: '',
    swatchId: '6500',
    color: '5DBFE4',
    BLName: 'Little Robots Blue',
    LName: 'Tiny Blue',
    OName: '',
    parts: '2',
    inSets: '2',
    type: '',
    colorTimeline: '2003-2004',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '269',
    Oid: '',
    swatchId: '6550',
    color: '3E95B6',
    BLName: '',
    LName: 'Tiny-Medium Blue',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '2004-2004',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '72',
    Lid: '11',
    Oid: '71',
    swatchId: '6600',
    color: '7DC1D8',
    BLName: 'Maersk Blue',
    LName: 'Pastel Blue',
    OName: 'Maersk Blue',
    parts: '84',
    inSets: '14',
    type: '',
    colorTimeline: '1974-2011',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '156',
    Lid: '322',
    Oid: '73',
    swatchId: '6700',
    color: '6ACEE0',
    BLName: 'Medium Azure',
    LName: 'Medium Azur',
    OName: 'Medium Azure',
    parts: '807',
    inSets: '1309',
    type: '',
    colorTimeline: '2012- ',
    flourescence: '',
    similar: ['232'],
    note: '',
  },
  {
    id: '87',
    Lid: '232',
    Oid: '88',
    swatchId: '6800',
    color: '8AD4E1',
    BLName: 'Sky Blue',
    LName: 'Dove Blue',
    OName: 'Sky Blue',
    parts: '37',
    inSets: '33',
    type: '',
    colorTimeline: '2003-2007',
    flourescence: '',
    similar: ['322'],
    note: '',
  },
  {
    id: '42',
    Lid: '102',
    Oid: '14',
    swatchId: '6900',
    color: '82ADD8',
    BLName: 'Medium Blue',
    LName: 'Medium Blue',
    OName: 'Medium Blue',
    parts: '789',
    inSets: '1098',
    type: '',
    colorTimeline: '1949- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '105',
    Lid: '212',
    Oid: '42',
    swatchId: '7000',
    color: 'BCD1ED',
    BLName: 'Bright Light Blue',
    LName: 'Light Royal Blue',
    OName: 'Bright Light Blue',
    parts: '440',
    inSets: '510',
    type: '',
    colorTimeline: '2004- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '62',
    Lid: '45',
    Oid: '63',
    swatchId: '7100',
    color: 'C8D9E1',
    BLName: 'Light Blue',
    LName: 'Light Blue',
    OName: 'Light Blue',
    parts: '20',
    inSets: '19',
    type: '',
    colorTimeline: '1950-2007',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '55',
    Lid: '135',
    Oid: '85',
    swatchId: '7200',
    color: '8899AB',
    BLName: 'Sand Blue',
    LName: 'Sand Blue',
    OName: 'Sand Blue',
    parts: '644',
    inSets: '589',
    type: '',
    colorTimeline: '2001- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '109',
    Lid: '196',
    Oid: '49',
    swatchId: '7300',
    color: '2032B0',
    BLName: 'Dark Blue-Violet',
    LName: 'Dark Royal Blue',
    OName: 'Dark Royal Blue',
    parts: '9',
    inSets: '7',
    type: '',
    colorTimeline: '2004-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '43',
    Lid: '110',
    Oid: '15',
    swatchId: '7400',
    color: '3448A4',
    BLName: 'Violet',
    LName: 'Bright Bluish Violet',
    OName: 'Violet',
    parts: '79',
    inSets: '43',
    type: '',
    colorTimeline: '1992-2004',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '97',
    Lid: '195',
    Oid: '40',
    swatchId: '7500',
    color: '506CEF',
    BLName: 'Blue-Violet',
    LName: 'Reddish Blue',
    OName: 'Royal Blue',
    parts: '38',
    inSets: '19',
    type: '',
    colorTimeline: '2004-2005',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '213',
    Oid: '',
    swatchId: '7550',
    color: '476FB6',
    BLName: '',
    LName: 'Medium Royal Blue',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '2004-2004',
    flourescence: '',
    similar: [],
    note: 'DUPLO Slope',
  },
  {
    id: '245',
    Lid: '219',
    Oid: '221',
    swatchId: '7600',
    color: '7862CE',
    BLName: 'Lilac',
    LName: 'Lilac',
    OName: 'Lilac',
    parts: '5',
    inSets: '6',
    type: '',
    colorTimeline: '2004-2005',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '73',
    Lid: '112',
    Oid: '78',
    swatchId: '7700',
    color: '9391E4',
    BLName: 'Medium Violet',
    LName: 'Medium (Light?) Bluish Violet',
    OName: 'Medium Violet',
    parts: '15',
    inSets: '19',
    type: '',
    colorTimeline: '1999-2004',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '246',
    Lid: '220',
    Oid: '',
    swatchId: '7800',
    color: 'CDCCEE',
    BLName: 'Light Lilac',
    LName: 'Light Lilac',
    OName: '',
    parts: '1',
    inSets: '1',
    type: '',
    colorTimeline: '2004-2004',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '44',
    Lid: '39',
    Oid: '16',
    swatchId: '7900',
    color: 'C9CAE2',
    BLName: 'Light Violet',
    LName: 'Light Bluish Violet',
    OName: 'Light Violet',
    parts: '69',
    inSets: '38',
    type: '',
    colorTimeline: '1994-2002',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '197',
    Oid: '',
    swatchId: '7950',
    color: '312B87',
    BLName: '',
    LName: 'Bright Lilac',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: '2003-2003',
    flourescence: '',
    similar: [],
    note: 'DUPLO 4x4',
  },
  {
    id: '89',
    Lid: '268',
    Oid: '55',
    swatchId: '8000',
    color: '5F2683',
    BLName: 'Dark Purple',
    LName: 'Medium Lilac',
    OName: 'Dark Purple',
    parts: '968',
    inSets: '1154',
    type: '',
    colorTimeline: '2000- ',
    flourescence: '',
    similar: ['104'],
    note: '',
  },
  {
    id: '24',
    Lid: '104',
    Oid: '4',
    swatchId: '8100',
    color: '7A238D',
    BLName: 'Purple',
    LName: 'Bright Violet',
    OName: 'Purple',
    parts: '136',
    inSets: '126',
    type: '',
    colorTimeline: '1996-2006',
    flourescence: '',
    similar: ['268'],
    note: '',
  },
  {
    id: '93',
    Lid: '198',
    Oid: '69',
    swatchId: '8200',
    color: 'AF3195',
    BLName: 'Light Purple',
    LName: 'Bright reddish Lilac',
    OName: 'Light Purple',
    parts: '26',
    inSets: '19',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '157',
    Lid: '324',
    Oid: '76',
    swatchId: '8300',
    color: 'C689D9',
    BLName: 'Medium Lavender',
    LName: 'Medium Lavender',
    OName: 'Medium Lavender',
    parts: '449',
    inSets: '628',
    type: '',
    colorTimeline: '2012- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '154',
    Lid: '325',
    Oid: '36',
    swatchId: '8400',
    color: 'D3BDE3',
    BLName: 'Lavender',
    LName: 'Lavender',
    OName: 'Lavender',
    parts: '310',
    inSets: '435',
    type: '',
    colorTimeline: '2011- ',
    flourescence: '',
    similar: ['218'],
    note: '',
  },
  {
    id: '227',
    Lid: '218',
    Oid: '223',
    swatchId: '8500',
    color: 'E0AAD9',
    BLName: 'Clikits Lavender',
    LName: 'Reddish Lilac',
    OName: 'Very Light Purple',
    parts: '10',
    inSets: '12',
    type: '',
    colorTimeline: '2005-2005',
    flourescence: '',
    similar: ['325'],
    note: 'Clikits-only color',
  },
  {
    id: '54',
    Lid: '136',
    Oid: '86',
    swatchId: '8600',
    color: 'B57DA5',
    BLName: 'Sand Purple',
    LName: 'Sand Violet',
    OName: 'Sand Purple',
    parts: '20',
    inSets: '5',
    type: '',
    colorTimeline: '2001-2002',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '71',
    Lid: '124',
    Oid: '72',
    swatchId: '8700',
    color: 'B72276',
    BLName: 'Magenta',
    LName: 'Bright Reddish Violet',
    OName: 'Magenta',
    parts: '563',
    inSets: '907',
    type: '',
    colorTimeline: '2000- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '47',
    Lid: '221',
    Oid: '17',
    swatchId: '8800',
    color: 'EF5BB3',
    BLName: 'Dark Pink',
    LName: 'Bright Purple',
    OName: 'Dark Pink',
    parts: '721',
    inSets: '1169',
    type: '',
    colorTimeline: '2003- ',
    flourescence: '',
    similar: ['22', '295'],
    note: '',
  },
  {
    id: '',
    Lid: '22',
    Oid: '',
    swatchId: '8850',
    color: 'EF5BB3',
    BLName: '',
    LName: 'Medium Reddish Violet',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '1994-2003',
    flourescence: '',
    similar: ['221', '295'],
    note: 'Old Dark Pink',
  },
  {
    id: '47',
    Lid: '295',
    Oid: '',
    swatchId: '8900',
    color: 'EF5BB3',
    BLName: 'Clikits-Dark Pink*',
    LName: 'Flamingo Pink',
    OName: '',
    parts: '33',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: ['221'],
    note: 'Clikits-only color',
  },
  {
    id: '94',
    Lid: '16',
    Oid: '75',
    swatchId: '9000',
    color: 'F785B1',
    BLName: 'Medium Dark Pink',
    LName: 'Pink',
    OName: 'Medium Dark Pink',
    parts: '14',
    inSets: '6',
    type: '',
    colorTimeline: '1992-1993',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '104',
    Lid: '222',
    Oid: '45',
    swatchId: '9100',
    color: 'F7BCDA',
    BLName: 'Bright Pink',
    LName: 'Light Purple',
    OName: 'Bright Pink',
    parts: '575',
    inSets: '1148',
    type: '',
    colorTimeline: '2003- ',
    flourescence: '',
    similar: ['9', '17'],
    note: '',
  },
  {
    id: '23',
    Lid: '9',
    Oid: '3',
    swatchId: '9200',
    color: 'F5CDD6',
    BLName: 'Pink',
    LName: 'Light Reddish Violet',
    OName: 'Pink',
    parts: '119',
    inSets: '77',
    type: '',
    colorTimeline: '1991-2005',
    flourescence: '',
    similar: ['222', '17'],
    note: '',
  },
  {
    id: '56',
    Lid: '17',
    Oid: '68',
    swatchId: '9300',
    color: 'FFE1FF',
    BLName: 'Light Pink',
    LName: 'Rose',
    OName: 'Light Pink',
    parts: '3',
    inSets: '4',
    type: '',
    colorTimeline: '1999-2007',
    flourescence: '',
    similar: ['100', '9', '222'],
    note: 'Paradisa Pink',
  },
];

let a1 = solidColors.map((color) => ({ ...color, type: 'solid' }));

let transparentColors = [
  {
    id: '12',
    Lid: '40',
    Oid: '97',
    swatchId: '15000',
    color: 'EEEEEE',
    BLName: 'Trans-Clear',
    LName: 'Transparent',
    OName: 'Transparent',
    parts: '968',
    inSets: '4910',
    type: '',
    colorTimeline: '1950- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '13',
    Lid: '111',
    Oid: '95',
    swatchId: '15100',
    color: '939484',
    BLName: 'Trans-Brown',
    LName: 'Transparent Brown',
    OName: 'Transparent Black (<2023)',
    parts: '451',
    inSets: '1733',
    type: '',
    colorTimeline: '1999- ',
    flourescence: '',
    similar: ['375'],
    note: '',
  },

  {
    id: '251',
    Lid: '375',
    Oid: '235',
    swatchId: '15150',
    color: '777777',
    BLName: 'Trans-Black',
    LName: 'Transparent Black',
    OName: 'Transparent Black (2023)',
    parts: '1',
    inSets: '1',
    type: '',
    colorTimeline: '2023- ',
    flourescence: '',
    similar: ['111'],
    note: '',
  },
  {
    id: '17',
    Lid: '41',
    Oid: '108',
    swatchId: '15200',
    color: '9C0010',
    BLName: 'Trans-Red',
    LName: 'Transparent Red',
    OName: 'Transparent Red',
    parts: '216',
    inSets: '3639',
    type: '',
    colorTimeline: '1969- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '18',
    Lid: '47',
    Oid: '161',
    swatchId: '15300',
    color: 'FF4231',
    BLName: 'Trans-Neon Orange',
    LName: 'Transparent Flourescent Reddish Orange',
    OName: 'Transparent Neon Reddish Orange',
    parts: '241',
    inSets: '1037',
    type: '',
    colorTimeline: '1993- ',
    flourescence: '',
    similar: ['182'],
    note: '',
  },
  {
    id: '98',
    Lid: '182',
    Oid: '105',
    swatchId: '15400',
    color: 'D04010',
    BLName: 'Trans-Orange',
    LName: 'Transparent Bright Orange',
    OName: 'Transparent Orange',
    parts: '216',
    inSets: '1908',
    type: '',
    colorTimeline: '2003- ',
    flourescence: '',
    similar: ['231', '47'],
    note: '',
  },
  {
    id: '164',
    Lid: '231',
    Oid: '171',
    swatchId: '15500',
    color: 'E99A3A',
    BLName: 'Trans-Light Orange',
    LName: 'Transparent Flourescent Yellowish Orange',
    OName: 'Transparent Light Orange',
    parts: '42',
    inSets: '22',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: ['182'],
    note: '',
  },
  {
    id: '121',
    Lid: '157',
    Oid: '104',
    swatchId: '15600',
    color: 'FFD700',
    BLName: 'Trans-Neon Yellow',
    LName: 'Transparent Flourescent Yellow',
    OName: 'Transparent Neon Yellow',
    parts: '28',
    inSets: '37',
    type: '',
    colorTimeline: '2001-2006',
    flourescence: '',
    similar: ['234', '44', '49'],
    note: '',
  },
  {
    id: '',
    Lid: '234',
    Oid: '162',
    swatchId: '15650',
    color: 'FFD700',
    BLName: '',
    LName: 'Transparent Fire Yellow',
    OName: 'Transparent Fire Yellow',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: ['157', '44', '49'],
    note: 'Clikits-only color, Different than TrNeonYellow, but BL labels them together',
  },
  {
    id: '19',
    Lid: '44',
    Oid: '109',
    swatchId: '15700',
    color: 'EBF72D',
    BLName: 'Trans-Yellow',
    LName: 'Transparent Yellow',
    OName: 'Transparent Yellow',
    parts: '211',
    inSets: '2425',
    type: '',
    colorTimeline: '1969- ',
    flourescence: '',
    similar: ['157', '234'],
    note: '',
  },
  {
    id: '16',
    Lid: '49',
    Oid: '103',
    swatchId: '15800',
    color: 'C0F500',
    BLName: 'Trans-Neon Green',
    LName: 'Transparent Flourescent Green',
    OName: 'Transparent Neon Green',
    parts: '233',
    inSets: '1128',
    type: '',
    colorTimeline: '1990- ',
    flourescence: '',
    similar: ['311', '157', '234'],
    note: '',
  },
  {
    id: '108',
    Lid: '311',
    Oid: '96',
    swatchId: '15900',
    color: '10Cb31',
    BLName: 'Trans-Bright Green',
    LName: 'Transparent Bright Green',
    OName: 'Transparent Bright Green',
    parts: '159',
    inSets: '464',
    type: '',
    colorTimeline: '2006- ',
    flourescence: '',
    similar: ['49', '285', '227'],
    note: '',
  },
  {
    id: '221',
    Lid: '285',
    Oid: '191',
    swatchId: '16000',
    color: '94E5AB',
    BLName: 'Trans-Light Green',
    LName: 'Transparent Light Green',
    OName: 'Transparent Light Green',
    parts: '11',
    inSets: '5',
    type: '',
    colorTimeline: '2005-2006',
    flourescence: '',
    similar: ['311', '227'],
    note: '',
  },
  {
    id: '226',
    Lid: '227',
    Oid: '205',
    swatchId: '16100',
    color: '71EB54',
    BLName: 'Trans-Light Bright Green',
    LName: 'Transparent Bright Yellowish Green',
    OName: 'Transparent Light Bright Green',
    parts: '26',
    inSets: '18',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: ['285', '311'],
    note: '',
  },
  {
    id: '20',
    Lid: '48',
    Oid: '100',
    swatchId: '16200',
    color: '217625',
    BLName: 'Trans-Green',
    LName: 'Transparent Green',
    OName: 'Transparent Green',
    parts: '137',
    inSets: '1452',
    type: '',
    colorTimeline: '1969- ',
    flourescence: '',
    similar: [],
    note: '',
  },

  {
    id: '',
    Lid: '156',
    Oid: '',
    swatchId: '16250',
    color: '00296B',
    BLName: '',
    LName: 'Transparent Deep Blue',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Transparent',
    colorTimeline: '2000-2002',
    flourescence: '',
    similar: [],
    note: 'Only used in watch links, reacts under a blacklight differently than normal trans-blue',
  },
  {
    id: '14',
    Lid: '43',
    Oid: '98',
    swatchId: '16300',
    color: '00296B',
    BLName: 'Trans-Dark Blue',
    LName: 'Transparent Blue',
    OName: 'Transparent Dark Blue',
    parts: '263',
    inSets: '1659',
    type: '',
    colorTimeline: '1978- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '74',
    Lid: '143',
    Oid: '102',
    swatchId: '16400',
    color: '7384A5',
    BLName: 'Trans-Medium Blue',
    LName: 'Transparent Flourescent Blue',
    OName: 'Transparent Medium Blue',
    parts: '106',
    inSets: '210',
    type: '',
    colorTimeline: '2001-2018',
    flourescence: '',
    similar: ['293', '42'],
    note: '',
  },
  {
    id: '',
    Lid: '293',
    Oid: '163',
    swatchId: '16450',
    color: '7384A5',
    BLName: '',
    LName: 'Transparent Light Royal Blue',
    OName: 'Transparent Light Royal Blue',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2005-2005',
    flourescence: '',
    similar: ['143', '42'],
    note: 'Clikits-only color, Different than TrMedBlue, but BL labels them together',
  },
  {
    id: '15',
    Lid: '42',
    Oid: '101',
    swatchId: '16500',
    color: '68BCC5',
    BLName: 'Trans-Light Blue',
    LName: 'Transparent Light Blue',
    OName: 'Transparent Light Blue',
    parts: '773',
    inSets: '2794',
    type: '',
    colorTimeline: '1985- ',
    flourescence: '',
    similar: ['143', '293', '229'],
    note: '',
  },
  {
    id: '113',
    Lid: '229',
    Oid: '25',
    swatchId: '16600',
    color: 'B7C8BF',
    BLName: 'Trans-Aqua',
    LName: 'Transparent Light Bluish Green',
    OName: 'Transparent Very Light Blue',
    parts: '40',
    inSets: '38',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: ['42'],
    note: '',
  },
  {
    id: '114',
    Lid: '284',
    Oid: '26',
    swatchId: '16700',
    color: 'B97AB1',
    BLName: 'Trans-Light Purple',
    LName: 'Transparent Reddish Lilac',
    OName: 'Transparent Light Purple',
    parts: '20',
    inSets: '20',
    type: '',
    colorTimeline: '2005-2006',
    flourescence: '',
    similar: ['236'],
    note: '',
  },
  {
    id: '234',
    Lid: '236',
    Oid: '',
    swatchId: '16800',
    color: '9C41B6',
    BLName: 'Trans-Medium Purple',
    LName: 'Transparent Bright Reddish Lilac',
    OName: '',
    parts: '37',
    inSets: '35',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: ['284'],
    note: '',
  },
  {
    id: '51',
    Lid: '126',
    Oid: '107',
    swatchId: '16900',
    color: '5525B7',
    BLName: 'Trans-Purple',
    LName: 'Transparent Bright Bluish Violet',
    OName: 'Transparent Purple',
    parts: '131',
    inSets: '360',
    type: '',
    colorTimeline: '2000- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '50',
    Lid: '113',
    Oid: '99',
    swatchId: '17000',
    color: 'CE1d9b',
    BLName: 'Trans-Dark Pink',
    LName: 'Transparent Medium Reddish Violet',
    OName: 'Transparent Dark Pink',
    parts: '236',
    inSets: '688',
    type: '',
    colorTimeline: '1998- ',
    flourescence: '',
    similar: ['230', '158'],
    note: '',
  },
  {
    id: '50',
    Lid: '158',
    Oid: '',
    swatchId: '17100',
    color: 'F18EBB',
    BLName: 'Trans-Dark Pink*',
    LName: 'Transparent Flourescent Red',
    OName: '',
    parts: '1',
    inSets: '',
    type: '',
    colorTimeline: '2001-2004',
    flourescence: '',
    similar: ['41'],
    note: 'Tahu Brain',
  },
  {
    id: '107',
    Lid: '230',
    Oid: '106',
    swatchId: '17200',
    color: 'FF8298',
    BLName: 'Trans-Pink',
    LName: 'Transparent Bright Purple',
    OName: 'Transparent Pink',
    parts: '68',
    inSets: '44',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: ['113'],
    note: '',
  },
];
let a2 = transparentColors.map((color) => ({ ...color, type: 'transparent' }));

let chromeColors = [
  {
    id: '21',
    Lid: '310',
    Oid: '2',
    swatchId: '20000',
    color: 'f1f2e1',
    BLName: 'Chrome Gold',
    LName: 'Metalized Gold',
    OName: 'Chrome Gold',
    parts: '52',
    inSets: '282',
    type: '',
    colorTimeline: '1989- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '20100',
    color: 'CC9900',
    BLName: 'Chrome Gold*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Employee exclusive, slightly warmer than regular chrome gold',
  },
  {
    id: '22',
    Lid: '309',
    Oid: '115',
    swatchId: '20200',
    color: 'DCDCDC',
    BLName: 'Chrome Silver',
    LName: 'Metalized Silver',
    OName: 'Chrome Silver',
    parts: '105',
    inSets: '561',
    type: '',
    colorTimeline: '1966-2018',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '57',
    Lid: '',
    Oid: '110',
    swatchId: '20300',
    color: '645a4c',
    BLName: 'Chrome Antique Brass',
    LName: 'Antique Gold',
    OName: 'Chrome Brass',
    parts: '3',
    inSets: '16',
    type: '',
    colorTimeline: '2001-2005',
    flourescence: '',
    similar: ['310'],
    note: '',
  },
  {
    id: '122',
    Lid: '',
    Oid: '111',
    swatchId: '20400',
    color: '544E4F',
    BLName: 'Chrome Black',
    LName: '',
    OName: 'Chrome Black',
    parts: '11',
    inSets: '1',
    type: '',
    colorTimeline: '2009-2009',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '20500',
    color: 'B30006',
    BLName: 'Chrome Red*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Only used in a keychain and supposedly a limited monochrome fig',
  },
  {
    id: '52',
    Lid: '',
    Oid: '112',
    swatchId: '20600',
    color: '5C66A4',
    BLName: 'Chrome Blue',
    LName: '',
    OName: 'Chrome Blue',
    parts: '5',
    inSets: '14',
    type: '',
    colorTimeline: '1998-2006',
    flourescence: '',
    similar: [],
    note: 'Has variation in color',
  },
  {
    id: '64',
    Lid: '',
    Oid: '113',
    swatchId: '20700',
    color: '3CB371',
    BLName: 'Chrome Green',
    LName: '',
    OName: 'Chrome Green',
    parts: '1',
    inSets: '2',
    type: '',
    colorTimeline: '1999-1999',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '82',
    Lid: '',
    Oid: '114',
    swatchId: '20800',
    color: 'aa4d8e',
    BLName: 'Chrome Pink',
    LName: '',
    OName: 'Chrome Pink',
    parts: '1',
    inSets: '10',
    type: '',
    colorTimeline: '2001-2007',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '20900',
    color: 'F5CDD6',
    BLName: 'Chrome Rose Gold*',
    LName: '',
    OName: '',
    parts: '1',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Only used in a keychain',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '22000',
    color: 'FFFFFF',
    BLName: 'Iridescent White*',
    LName: '',
    OName: '',
    parts: '1',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Only used in a keychain',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '22100',
    color: '68BCC5',
    BLName: 'Iridescent Blue*',
    LName: '',
    OName: '',
    parts: '2',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Only used in a keychain and one hair piece',
  },
];
let a3 = chromeColors.map((color) => ({ ...color, type: 'chrome' }));

let pearlColors = [
  {
    id: '83',
    Lid: '183',
    Oid: '123',
    swatchId: '25000',
    color: 'F6F2DF',
    BLName: 'Pearl White',
    LName: 'Metallic White',
    OName: 'Pearl White',
    parts: '3',
    inSets: '5',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '119',
    Lid: '150',
    Oid: '27',
    swatchId: '25100',
    color: 'D4D2CD',
    BLName: 'Pearl Very Light Gray',
    LName: 'Metallic Light Grey',
    OName: 'Pearl Very Light Gray',
    parts: '21',
    inSets: '15',
    type: '',
    colorTimeline: '2002-2004',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '66',
    Lid: '131',
    Oid: '122',
    swatchId: '25200',
    color: 'ACB7C0',
    BLName: 'Pearl Light Gray',
    LName: 'Silver',
    OName: 'Pearl Light Gray',
    parts: '435',
    inSets: '640',
    type: '',
    colorTimeline: '1993-2013',
    flourescence: '',
    similar: ['315'],
    note: '',
  },
  {
    id: '95',
    Lid: '315',
    Oid: '117',
    swatchId: '25300',
    color: '8D949C',
    BLName: 'Flat Silver',
    LName: 'Silver Metallic',
    OName: 'Flat Silver',
    parts: '919',
    inSets: '2763',
    type: '',
    colorTimeline: '2000- ',
    flourescence: '',
    similar: ['131', '179'],
    note: '',
  },
  {
    id: '239',
    Lid: '179',
    Oid: '229',
    swatchId: '25400',
    color: 'A59287',
    BLName: 'Bionicle Silver',
    LName: 'Silver Flip/Flop',
    OName: '',
    parts: '6',
    inSets: '3',
    type: '',
    colorTimeline: '2002-2002',
    flourescence: '',
    similar: ['315'],
    note: 'Only used in Bionicle masks',
  },
  {
    id: '77',
    Lid: '316',
    Oid: '119',
    swatchId: '25500',
    color: '666660',
    BLName: 'Pearl Dark Gray',
    LName: 'Titanium Metallic',
    OName: 'Pearl Dark Gray',
    parts: '704',
    inSets: '1069',
    type: '',
    colorTimeline: '2000- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '244',
    Lid: '149',
    Oid: '185',
    swatchId: '25600',
    color: '282725',
    BLName: 'Pearl Black',
    LName: 'Metallic Black',
    OName: 'Pearl Black',
    parts: '4',
    inSets: '8',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '61',
    Lid: '127',
    Oid: '121',
    swatchId: '25700',
    color: 'E7AE5A',
    BLName: 'Pearl Light Gold',
    LName: 'Gold',
    OName: 'Pearl Light Gold',
    parts: '13',
    inSets: '7',
    type: '',
    colorTimeline: '2000-2005',
    flourescence: '',
    similar: ['297'],
    note: '',
  },
  {
    id: '115',
    Lid: '297',
    Oid: '120',
    swatchId: '25800',
    color: 'E79E1D',
    BLName: 'Pearl Gold',
    LName: 'Warm Gold',
    OName: 'Pearl Gold',
    parts: '1024',
    inSets: '2154',
    type: '',
    colorTimeline: '2004- ',
    flourescence: '',
    similar: ['127', '189'],
    note: '',
  },
  {
    id: '235',
    Lid: '189',
    Oid: '215',
    swatchId: '25900',
    color: 'E7891B',
    BLName: 'Reddish Gold',
    LName: 'Reddish Gold/Gold Metallic',
    OName: 'Reddish Gold',
    parts: '28',
    inSets: '28',
    type: '',
    colorTimeline: '2003-2005',
    flourescence: '',
    similar: ['297', '346'],
    note: '',
  },
  {
    id: '238',
    Lid: '178',
    Oid: '231',
    swatchId: '26000',
    color: 'B9752F',
    BLName: 'Bionicle Gold',
    LName: 'Yellow Flip/Flop',
    OName: '',
    parts: '6',
    inSets: '3',
    type: '',
    colorTimeline: '2002-2002',
    flourescence: '',
    similar: ['297', '189'],
    note: 'Only used in Bionicle masks',
  },
  {
    id: '81',
    Lid: '147',
    Oid: '21',
    swatchId: '26100',
    color: 'AD7118',
    BLName: 'Flat Dark Gold',
    LName: 'Metallic Sand Yellow',
    OName: 'Flat Dark Gold',
    parts: '49',
    inSets: '47',
    type: '',
    colorTimeline: '2002-2006',
    flourescence: '',
    similar: ['178', '297'],
    note: '',
  },
  {
    id: '249',
    Lid: '346',
    Oid: '227',
    swatchId: '26200',
    color: 'D06926',
    BLName: 'Reddish Copper',
    LName: 'Copper Metallic',
    OName: 'Reddish Copper',
    parts: '21',
    inSets: '20',
    type: '',
    colorTimeline: '2017-2020',
    flourescence: '',
    similar: ['189', '176'],
    note: '',
  },
  {
    id: '84',
    Lid: '139',
    Oid: '116',
    swatchId: '26300',
    color: 'AC6D52',
    BLName: 'Copper',
    LName: 'Copper',
    OName: 'Copper',
    parts: '12',
    inSets: '23',
    type: '',
    colorTimeline: '2004-2008',
    flourescence: '',
    similar: ['346', '176'],
    note: '',
  },
  {
    id: '237',
    Lid: '176',
    Oid: '233',
    swatchId: '26400',
    color: '985750',
    BLName: 'Bionicle Copper',
    LName: 'Red Flip/Flop',
    OName: '',
    parts: '2',
    inSets: '1',
    type: '',
    colorTimeline: '2001-2001',
    flourescence: '',
    similar: ['139', '346'],
    note: 'Only used in Bionicle masks',
  },
  {
    id: '',
    Lid: '184',
    Oid: '181',
    swatchId: '26425',
    color: 'B30006',
    BLName: 'Pearl Red*',
    LName: 'Metallic Bright Red',
    OName: 'Pearl Red',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '187',
    Oid: '219',
    swatchId: '26435',
    color: '6B3F22',
    BLName: 'Pearl Brown*',
    LName: 'Metallic Earth Orange',
    OName: 'Pearl Brown',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '186',
    Oid: '183',
    swatchId: '26445',
    color: '00923D',
    BLName: 'Pearl Green*',
    LName: 'Metallic Dark Green',
    OName: 'Pearl Green',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '185',
    Oid: '189',
    swatchId: '26455',
    color: '0057A6',
    BLName: 'Pearl Blue*',
    LName: 'Metallic Bright Blue',
    OName: 'Pearl Blue',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2003-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '78',
    Lid: '145',
    Oid: '118',
    swatchId: '26500',
    color: '868FAA',
    BLName: 'Pearl Sand Blue',
    LName: 'Metallic Sand Blue',
    OName: 'Metallic Blue',
    parts: '45',
    inSets: '25',
    type: '',
    colorTimeline: '2002-2009',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '243',
    Lid: '146',
    Oid: '',
    swatchId: '26600',
    color: 'B5A1BA',
    BLName: 'Pearl Sand Purple',
    LName: 'Metallic Sand Violet',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never released in bricks, only wristwatch links, see part bb1007',
  },
];
let a4 = pearlColors.map((color) => ({ ...color, type: 'pearl' }));

let satinColors = [
  {
    id: '228',
    Lid: '360',
    Oid: '193',
    swatchId: '30000',
    color: 'FFFFFF',
    BLName: 'Satin Trans-Clear',
    LName: 'Transparent With Opalescence',
    OName: 'Transparent Opal',
    parts: '11',
    inSets: '33',
    type: '',
    colorTimeline: '2020- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '229',
    Lid: '363',
    Oid: '201',
    swatchId: '30100',
    color: '939484',
    BLName: 'Satin Trans-Brown',
    LName: 'Transparent Brown With Opalescence',
    OName: 'Transparent Black Opal',
    parts: '4',
    inSets: '9',
    type: '',
    colorTimeline: '2020-2021',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '30150',
    color: '777777',
    BLName: 'Satin Trans-Black*',
    LName: 'Transparent Black With Opalescence',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2023- ',
    flourescence: '',
    similar: ['363'],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '30200',
    color: '6A0E15',
    BLName: 'Satin Trans-Dark Red*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '361',
    Oid: '',
    swatchId: '30300',
    color: 'B30006',
    BLName: 'Satin Trans-Red*',
    LName: 'Transparent Red With Opalescence',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '30400',
    color: 'FF4231',
    BLName: 'Satin Trans-Neon Orange*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '30500',
    color: 'FF7E14',
    BLName: 'Satin Trans-Orange*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '376',
    Oid: '',
    swatchId: '30600',
    color: 'FFE001',
    BLName: 'Satin Trans-Yellow*',
    LName: 'Transparent Yellow With Opalescence',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '30700',
    color: 'DBF355',
    BLName: 'Satin Trans-Neon Green*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '233',
    Lid: '367',
    Oid: '207',
    swatchId: '30800',
    color: '7fe15b',
    BLName: 'Satin Trans-Bright Green',
    LName: 'Transparent Bright Green With Opalescence',
    OName: 'Transparent Green Opal',
    parts: '5',
    inSets: '4',
    type: '',
    colorTimeline: '2021- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '30900',
    color: '217625',
    BLName: 'Satin Trans-Green*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '223',
    Lid: '362',
    Oid: '175',
    swatchId: '31000',
    color: '68BCC5',
    BLName: 'Satin Trans-Light Blue',
    LName: 'Transparent Light Blue With Opalescence',
    OName: 'Transparent Blue Opal',
    parts: '26',
    inSets: '54',
    type: '',
    colorTimeline: '2020- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '232',
    Lid: '366',
    Oid: '209',
    swatchId: '31100',
    color: '1552e2',
    BLName: 'Satin Trans-Dark Blue',
    LName: 'Transparent Blue With Opalescence',
    OName: 'Transparent Dark Blue Opal',
    parts: '9',
    inSets: '7',
    type: '',
    colorTimeline: '2021- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '230',
    Lid: '365',
    Oid: '203',
    swatchId: '31200',
    color: '8320B7',
    BLName: 'Satin Trans-Purple',
    LName: 'Transparent Bright Violet With Opalescence',
    OName: 'Transparent Purple Opal',
    parts: '1',
    inSets: '5',
    type: '',
    colorTimeline: '2020-2020',
    flourescence: '',
    similar: [],
    note: '',
  },

  {
    id: '224',
    Lid: '364',
    Oid: '199',
    swatchId: '31300',
    color: 'CE1d9b',
    BLName: 'Satin Trans-Dark Pink',
    LName: 'Transparent Medium Reddish Violet With Opalescence',
    OName: 'Transparent Dark Pink Opal',
    parts: '7',
    inSets: '18',
    type: '',
    colorTimeline: '2020- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '361',
    Oid: '',
    swatchId: '31350',
    color: 'ffffff',
    BLName: '',
    LName: 'Opalescence 3%',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Satin',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
];
let a5 = satinColors.map((color) => ({ ...color, type: 'satin' }));

let metallicColors = [
  {
    id: '67',
    Lid: '298',
    Oid: '126',
    swatchId: '35000',
    color: 'C0C0C0',
    BLName: 'Metallic Silver',
    LName: 'Cool Silver, Drum Lacquered',
    OName: 'Metallic Silver',
    parts: '184',
    inSets: '665',
    type: '',
    colorTimeline: '1957- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '70',
    Lid: '',
    Oid: '125',
    swatchId: '35100',
    color: 'bdb573',
    BLName: 'Metallic Green',
    LName: '',
    OName: 'Metallic Green',
    parts: '31',
    inSets: '10',
    type: '',
    colorTimeline: '2001-2018',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '65',
    Lid: '299',
    Oid: '124',
    swatchId: '35200',
    color: 'B8860B',
    BLName: 'Metallic Gold',
    LName: 'Warm Gold, Drum Lacquered',
    OName: 'Metallic Gold',
    parts: '104',
    inSets: '274',
    type: '',
    colorTimeline: '1997- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '250',
    Lid: '300',
    Oid: '225',
    swatchId: '35300',
    color: 'C58259',
    BLName: 'Metallic Copper',
    LName: 'Copper, Drum Lacquered',
    OName: 'Metallic Copper',
    parts: '5',
    inSets: '13',
    type: '',
    colorTimeline: '2008-2012',
    flourescence: '',
    similar: [],
    note: '',
  },
];
let a6 = metallicColors.map((color) => ({ ...color, type: 'metallic' }));

let milkyColors = [
  {
    id: '60',
    Lid: '20',
    Oid: '130',
    swatchId: '40000',
    color: 'd4d3dd',
    BLName: 'Milky White',
    LName: 'Nature',
    OName: 'Translucent White',
    parts: '26',
    inSets: '144',
    type: '',
    colorTimeline: '1963-2008',
    flourescence: '',
    similar: ['122'],
    note: '',
  },
  {
    id: '159',
    Lid: '329',
    Oid: '129',
    swatchId: '40100',
    color: 'd9d9d9',
    BLName: 'Glow In Dark White',
    LName: 'White Glow',
    OName: 'Glow in the Dark Solid White',
    parts: '66',
    inSets: '71',
    type: '',
    colorTimeline: '2012- ',
    flourescence: '',
    similar: ['50'],
    note: '',
  },
  {
    id: '46',
    Lid: '50',
    Oid: '127',
    swatchId: '40200',
    color: 'd4d5c9',
    BLName: 'Glow In Dark Opaque',
    LName: 'Phosphorus White',
    OName: 'Glow in the Dark Transparent White',
    parts: '55',
    inSets: '88',
    type: '',
    colorTimeline: '1990-2011',
    flourescence: '',
    similar: ['329', '294'],
    note: '',
  },
  {
    id: '118',
    Lid: '294',
    Oid: '128',
    swatchId: '40300',
    color: 'bdc6ad',
    BLName: 'Glow In Dark Trans',
    LName: 'Phosphorus Green',
    OName: 'Glow in the Dark Transparent Green',
    parts: '16',
    inSets: '22',
    type: '',
    colorTimeline: '2005-2011',
    flourescence: '',
    similar: ['50'],
    note: '',
  },
];
let a7 = milkyColors.map((color) => ({ ...color, type: 'milky' }));

let glitterColors = [
  {
    id: '',
    Lid: '132',
    Oid: '',
    swatchId: '44800',
    color: '212121',
    BLName: 'Glitter Black*',
    LName: 'Black Glitter',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2000-2000',
    flourescence: '',
    similar: [],
    note: 'Container for 7159, never released in bricks',
  },
  {
    id: '',
    Lid: '122',
    Oid: '',
    swatchId: '44900',
    color: 'D4D3DD',
    BLName: 'Glitter Milky White*',
    LName: 'Nature with Glitter',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: ['20'],
    note: 'Never publicly released, Possibly the same as Allianz Arena?',
  },
  {
    id: '101',
    Lid: '117',
    Oid: '131',
    swatchId: '45000',
    color: 'b2adaa',
    BLName: 'Glitter Trans-Clear',
    LName: 'Transparent With Glitter',
    OName: 'Transparent Glitter',
    parts: '16',
    inSets: '29',
    type: '',
    colorTimeline: '1999- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '349',
    Oid: '',
    swatchId: '45100',
    color: '939484',
    BLName: 'Glitter Trans-Brown',
    LName: 'Transparent Brown with Glitter',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '45150',
    color: '777777',
    BLName: 'Glitter Trans-Black*',
    LName: 'Transparent Black with Glitter',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '2023- ',
    flourescence: '',
    similar: ['349'],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '173',
    Oid: '',
    swatchId: '45200',
    color: '9C0010',
    BLName: 'Glitter Trans-Red*',
    LName: 'Transparent Red Glitter',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '352',
    Oid: '',
    swatchId: '45300',
    color: 'FF4231',
    BLName: 'Glitter Trans-Neon Orange*',
    LName: 'Transparent Fluorescent Reddish Orange with Glitter',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Glitter',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released',
  },
  {
    id: '222',
    Lid: '341',
    Oid: '179',
    swatchId: '45400',
    color: 'D04010',
    BLName: 'Glitter Trans-Orange',
    LName: 'Transparent Bright Orange With Glitter',
    OName: 'Transparent Orange with Glitter',
    parts: '1',
    inSets: '1',
    type: '',
    colorTimeline: '2020-2020',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '348',
    Lid: '348',
    Oid: '',
    swatchId: '45500',
    color: 'EBF72D',
    BLName: 'Glitter Trans-Yellow*',
    LName: 'Transparent Yellow with Glitter',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '163',
    Lid: '339',
    Oid: '167',
    swatchId: '45600',
    color: 'C0F500',
    BLName: 'Glitter Trans-Neon Green',
    LName: 'Transparent Fluorescent Green With Glitter',
    OName: 'Transparent Neon Green Glitter',
    parts: '1',
    inSets: '8',
    type: '',
    colorTimeline: '2015-2018',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '351',
    Oid: '',
    swatchId: '45700',
    color: '10CB31',
    BLName: 'Glitter Trans-Bright Green*',
    LName: 'Transparent Bright Green with Glitter',
    OName: '',
    parts: '0',
    inSets: '0',
    type: '',
    colorTimeline: '- ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released',
  },
  {
    id: '',
    Lid: '155',
    Oid: '',
    swatchId: '45800',
    color: '217625',
    BLName: 'Glitter Trans-Green*',
    LName: 'Transparent Green Glitter',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released',
  },
  {
    id: '',
    Lid: '340',
    Oid: '',
    swatchId: '45900',
    color: '00296B',
    BLName: 'Glitter Trans-Dark Blue*',
    LName: 'Transparent Blue Glitter',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Never publicly released, only available through factory leaks',
  },
  {
    id: '',
    Lid: '350',
    Oid: '',
    swatchId: '46000',
    color: '7384A5',
    BLName: 'Glitter Trans-Medium Blue*',
    LName: 'Transparent Fluorescent Blue with Glitter',
    OName: '',
    parts: '0',
    inSets: '0',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '162',
    Lid: '302',
    Oid: '165',
    swatchId: '46100',
    color: '68BCC5',
    BLName: 'Glitter Trans-Light Blue',
    LName: 'Transparent Light Blue With Glitter',
    OName: 'Transparent Light Blue Glitter',
    parts: '17',
    inSets: '27',
    type: '',
    colorTimeline: '2015- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '303',
    Oid: '',
    swatchId: '46150',
    color: 'B97AB1',
    BLName: '',
    LName: 'Transparent Br Reddish Lilac w/ Glitter',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Transparent',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'clikits',
  },
  {
    id: '102',
    Lid: '129',
    Oid: '22',
    swatchId: '46200',
    color: '3A2B82',
    BLName: 'Glitter Trans-Purple',
    LName: 'Transparent Bright Blue/Violet With Glitter',
    OName: 'Transparent Purple Glitter',
    parts: '10',
    inSets: '49',
    type: '',
    colorTimeline: '2000- ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '100',
    Lid: '114',
    Oid: '132',
    swatchId: '46300',
    color: 'CE1d9b',
    BLName: 'Glitter Trans-Dark Pink',
    LName: 'Transparent Medium Reddish Violet With Glitter',
    OName: 'Transparent Pink Glitter',
    parts: '12',
    inSets: '39',
    type: '',
    colorTimeline: '1999- ',
    flourescence: '',
    similar: [],
    note: '',
  },
];
let a8 = glitterColors.map((color) => ({ ...color, type: 'glitter' }));

let speckleColors = [
  {
    id: '111',
    Lid: '304',
    Oid: '24',
    swatchId: '50100',
    color: '7C7E7C',
    BLName: 'Speckle Black-Silver',
    LName: 'Cool Silver, Diffuse',
    OName: 'Speckle Black',
    parts: '15',
    inSets: '49',
    type: '',
    colorTimeline: '2005-2013',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '151',
    Lid: '',
    Oid: '35',
    swatchId: '50200',
    color: 'AB9421',
    BLName: 'Speckle Black-Gold',
    LName: '',
    OName: 'Speckle Black Gold',
    parts: '2',
    inSets: '4',
    type: '',
    colorTimeline: '2010-2011',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '116',
    Lid: '306',
    Oid: '133',
    swatchId: '50300',
    color: '5F4E47',
    BLName: 'Speckle Black-Copper',
    LName: 'Copper, Diffuse',
    OName: 'Speckle Black Copper',
    parts: '5',
    inSets: '3',
    type: '',
    colorTimeline: '2006-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '117',
    Lid: '304',
    Oid: '134',
    swatchId: '50400',
    color: '4A6363',
    BLName: 'Speckle DBGray-Silver',
    LName: 'Cool, Silver Diffuse',
    OName: 'Speckle Gray',
    parts: '5',
    inSets: '7',
    type: '',
    colorTimeline: '2006-2006',
    flourescence: '',
    similar: [],
    note: '',
  },
];
let a9 = speckleColors.map((color) => ({ ...color, type: 'speckle' }));

let modulexColors = [
  {
    id: '123',
    Lid: '1/31',
    Oid: '154',
    swatchId: '90000',
    color: 'FFFFFF',
    BLName: 'Mx White',
    LName: 'White',
    OName: 'Modulex White',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '124',
    Lid: '32',
    Oid: '28',
    swatchId: '90100',
    color: 'AfB5C7',
    BLName: 'Mx Light Bluish Gray',
    LName: 'Light Bluish Gray',
    OName: 'Modulex Medium Stone Gray',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '125',
    Lid: '2',
    Oid: '141',
    swatchId: '90200',
    color: '9C9C9C',
    BLName: 'Mx Light Gray',
    LName: 'Light Gray',
    OName: 'Modulex Light Gray',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '126',
    Lid: '40',
    Oid: '29',
    swatchId: '90300',
    color: '595D60',
    BLName: 'Mx Charcoal Gray',
    LName: 'Charcoal Gray',
    OName: 'Modulex Charcoal Gray',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '127',
    Lid: '',
    Oid: '152',
    swatchId: '90400',
    color: '6B5A5A',
    BLName: 'Mx Tile Gray',
    LName: '',
    OName: 'Modulex Tile Gray',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '128',
    Lid: '3',
    Oid: '136',
    swatchId: '90500',
    color: '000000',
    BLName: 'Mx Black',
    LName: 'Black',
    OName: 'Modulex Black',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '131',
    Lid: '',
    Oid: '151',
    swatchId: '90600',
    color: '330000',
    BLName: 'Mx Tile Brown',
    LName: '',
    OName: 'Modulex Tile Brown',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '134',
    Lid: '4',
    Oid: '150',
    swatchId: '90700',
    color: '5C5030',
    BLName: 'Mx Terracotta',
    LName: 'Terracotta',
    OName: 'Modulex Terracotta',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '132',
    Lid: '9',
    Oid: '137',
    swatchId: '90800',
    color: '907450',
    BLName: 'Mx Brown',
    LName: 'Brown',
    OName: 'Modulex Brown',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '133',
    Lid: '5',
    Oid: '138',
    swatchId: '90900',
    color: 'DEC69C',
    BLName: 'Mx Buff',
    LName: 'Buff',
    OName: 'Modulex Buff',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '129',
    Lid: '13',
    Oid: '148',
    swatchId: '91000',
    color: 'B52C20',
    BLName: 'Mx Red',
    LName: 'Red',
    OName: 'Modulex Red',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '130',
    Lid: '33',
    Oid: '147',
    swatchId: '91100',
    color: 'F45C40',
    BLName: 'Mx Pink Red',
    LName: 'Pink Red',
    OName: 'Modulex Pink Red',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '135',
    Lid: '12',
    Oid: '30',
    swatchId: '91200',
    color: 'F47B30',
    BLName: 'Mx Orange',
    LName: 'Orange',
    OName: 'Modulex Orange',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '136',
    Lid: '39',
    Oid: '142',
    swatchId: '91300',
    color: 'F7AD63',
    BLName: 'Mx Light Orange',
    LName: 'Light Orange',
    OName: 'Modulex Light Orange',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '137',
    Lid: '35',
    Oid: '143',
    swatchId: '91400',
    color: 'FFE371',
    BLName: 'Mx Light Yellow',
    LName: 'Light Yellow',
    OName: 'Modulex Light Yellow',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '138',
    Lid: '6',
    Oid: '31',
    swatchId: '91500',
    color: 'FED557',
    BLName: 'Mx Ochre Yellow',
    LName: 'Ocher Yellow',
    OName: 'Modulex Ochre Yellow',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '139',
    Lid: '15',
    Oid: '140',
    swatchId: '91600',
    color: 'BDC618',
    BLName: 'Mx Lemon',
    LName: 'Lemon',
    OName: 'Modulex Lemon',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '141',
    Lid: '14',
    Oid: '33',
    swatchId: '91700',
    color: '7DB538',
    BLName: 'Mx Pastel Green',
    LName: 'Pastel Green',
    OName: 'Modulex Pastel Green',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '140',
    Lid: '7',
    Oid: '32',
    swatchId: '91800',
    color: '7C9051',
    BLName: 'Mx Olive Green',
    LName: 'Olive Green',
    OName: 'Modulex Olive Green',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '142',
    Lid: '34',
    Oid: '135',
    swatchId: '91900',
    color: '27867E',
    BLName: 'Mx Aqua Green',
    LName: 'Aqua Green',
    OName: 'Modulex Aqua Green',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '146',
    Lid: '8',
    Oid: '149',
    swatchId: '92000',
    color: '467083',
    BLName: 'Mx Teal Blue',
    LName: 'Teal Blue',
    OName: 'Modulex Teal Blue',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '143',
    Lid: '',
    Oid: '34',
    swatchId: '92100',
    color: '0057A6',
    BLName: 'Mx Tile Blue',
    LName: '',
    OName: 'Modulex Tile Blue',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '144',
    Lid: '38',
    Oid: '144',
    swatchId: '92200',
    color: '61AFFF',
    BLName: 'Mx Medium Blue',
    LName: 'Medium Blue',
    OName: 'Modulex Medium Blue',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '145',
    Lid: '11',
    Oid: '145',
    swatchId: '92300',
    color: '68AECE',
    BLName: 'Mx Pastel Blue',
    LName: 'Pastel Blue',
    OName: 'Modulex Pastel Blue',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '147',
    Lid: '37',
    Oid: '153',
    swatchId: '92400',
    color: 'BD7D85',
    BLName: 'Mx Violet',
    LName: 'Violet',
    OName: 'Modulex Violet',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '148',
    Lid: '16',
    Oid: '146',
    swatchId: '92500',
    color: 'F785B1',
    BLName: 'Mx Pink',
    LName: 'Pink',
    OName: 'Modulex Pink',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '149',
    Lid: '10',
    Oid: '139',
    swatchId: '92600',
    color: 'FFFFFF',
    BLName: 'Mx Clear',
    LName: 'Clear',
    OName: 'Modulex Clear',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '10',
    Oid: '',
    swatchId: '92700',
    color: 'UNKNWN',
    BLName: 'Mx Strong Red*',
    LName: 'Strong Red*',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' -1997',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '92800',
    color: 'UNKNWN',
    BLName: 'Mx Ice White*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Plancopy baseplates',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '92900',
    color: 'UNKNWN',
    BLName: 'Mx Very Light Bluish Gray*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: '1997-2006',
    flourescence: '',
    similar: [],
    note: 'Plancopy baseplates',
  },
  {
    id: '',
    Lid: '',
    Oid: '',
    swatchId: '93000',
    color: 'UNKNWN',
    BLName: 'Mx Dark Gray*',
    LName: '',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Plancopy baseplates',
  },
];
let a10 = modulexColors.map((color) => ({ ...color, type: 'modulex' }));

let modulexFoilColors = [
  {
    id: '',
    Lid: '80',
    Oid: '',
    swatchId: '97500',
    color: 'FFFFFF',
    BLName: 'Mx Foil White*',
    LName: 'White',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '',
    Lid: '81',
    Oid: '',
    swatchId: '97600',
    color: '000000',
    BLName: 'Mx Foil Black*',
    LName: 'Black',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '210',
    Lid: '82',
    Oid: '',
    swatchId: '97700',
    color: '595D60',
    BLName: 'Mx Foil Dark Gray',
    LName: 'Dark Gray',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '211',
    Lid: '83',
    Oid: '',
    swatchId: '97800',
    color: '9C9C9C',
    BLName: 'Mx Foil Light Gray',
    LName: 'Light Gray',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '212',
    Lid: '84',
    Oid: '',
    swatchId: '97900',
    color: '006400',
    BLName: 'Mx Foil Dark Green',
    LName: 'Dark Green',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '213',
    Lid: '85',
    Oid: '',
    swatchId: '98000',
    color: '7DB538',
    BLName: 'Mx Foil Light Green',
    LName: 'Light Green',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '214',
    Lid: '86',
    Oid: '',
    swatchId: '98100',
    color: '0057A6',
    BLName: 'Mx Foil Dark Blue',
    LName: 'Dark Blue',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '215',
    Lid: '87',
    Oid: '',
    swatchId: '98200',
    color: '68AECE',
    BLName: 'Mx Foil Light Blue',
    LName: 'Light Blue',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '216',
    Lid: '88',
    Oid: '',
    swatchId: '98300',
    color: '4B0082',
    BLName: 'Mx Foil Violet',
    LName: 'Violet',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '217',
    Lid: '89',
    Oid: '',
    swatchId: '98400',
    color: '8B0000',
    BLName: 'Mx Foil Red',
    LName: 'Red',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '218',
    Lid: '90',
    Oid: '',
    swatchId: '98500',
    color: 'FED557',
    BLName: 'Mx Foil Yellow',
    LName: 'Yellow',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
  {
    id: '219',
    Lid: '91',
    Oid: '',
    swatchId: '98600',
    color: 'F7AD63',
    BLName: 'Mx Foil Orange',
    LName: 'Orange',
    OName: '',
    parts: '',
    inSets: '',
    type: '',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Not a plastic color, no bricks were produced in Mx Foil',
  },
];
let a11 = modulexFoilColors.map((color) => ({ ...color, type: 'modulexFoil' }));

let functional = [
  {
    id: '',
    Lid: '109',
    Oid: '',
    swatchId: '201200',
    color: '001414',
    BLName: '',
    LName: '(PC) Black IR',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Transparent',
    colorTimeline: '1998-2016',
    flourescence: '',
    similar: [],
    note: '',
  },
  {
    id: '',
    Lid: '342',
    Oid: '',
    swatchId: '205400',
    color: '111111',
    BLName: '',
    LName: 'Conductive Black',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Other',
    colorTimeline: '2015-2015',
    flourescence: '',
    similar: [],
    note: 'special ABS with suspected fiberglass mixture',
  },
  {
    id: '',
    Lid: '343',
    Oid: '',
    swatchId: '205500',
    color: 'F5F5F5',
    BLName: '',
    LName: 'Diffuse White',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Milky',
    colorTimeline: '2016- ',
    flourescence: '',
    similar: [],
    note: 'Infrared cover for 19071c01',
  },
  {
    id: '',
    Lid: '354',
    Oid: '',
    swatchId: '206300',
    color: 'F5F5F5',
    BLName: '',
    LName: 'High Tr. Diff. White',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Milky',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'bumper for 28743c01',
  },
  {
    id: '',
    Lid: '355',
    Oid: '',
    swatchId: '206400',
    color: '000000',
    BLName: '',
    LName: 'Tr. Black IR',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Transparent',
    colorTimeline: '2017- ',
    flourescence: '',
    similar: [],
    note: 'newer IR covers',
  },
  {
    id: '',
    Lid: '358',
    Oid: '',
    swatchId: '206600',
    color: 'F4F4F4',
    BLName: '',
    LName: 'Translucent White',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Milky',
    colorTimeline: '2020- ',
    flourescence: '',
    similar: [],
    note: 'Robot Inventor and Spike Prime hubs',
  },
  {
    id: '',
    Lid: '369',
    Oid: '',
    swatchId: '206800',
    color: 'F5F5F5',
    BLName: '',
    LName: 'Light Block. White',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Milky',
    colorTimeline: '2021- ',
    flourescence: '',
    similar: [],
    note: '47592c01',
  },
];
let a12 = functional.map((color) => ({ ...color, type: 'functional' }));

let unreleased = [
  {
    id: '',
    Lid: '7',
    Oid: '',
    swatchId: '200100',
    color: 'FF8500',
    BLName: '',
    LName: 'Orange',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unreleased',
  },

  {
    id: '',
    Lid: '8',
    Oid: '',
    swatchId: '200200',
    color: '8C00FF',
    BLName: '',
    LName: 'Cobalt Blue',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unreleased',
  },

  // {
  //   id: "",
  //   Lid: "10",
  //Oid: '',//
  //swatchId: "2003",
  //   color: "FFFFBB",
  //   BLName: "",
  //   LName: "Clear* / Transparent*",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Transparent",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },

  // {
  //   id: '',
  //   Lid: '10',
  //Oid: '',//
  //swatchId: '2005',
  //   color: 'ffffff',
  //   BLName: '',
  //   LName: 'Clear',
  //   OName: '',
  //   parts: '0',
  //   inSets: '0',
  //   type: 'Modulex',
  //   colorTimeline: '1983-1993',
  //   flourescence: '',
  //   similar: [],
  //   note: '',
  // },

  // {
  //   id: '',
  //   Lid: '31',
  //Oid: '',//
  //swatchId: '2008',
  //   color: 'ffffff',
  //   BLName: '',
  //   LName: 'White',
  //   OName: '',
  //   parts: '0',
  //   inSets: '0',
  //   type: 'Modulex',
  //   colorTimeline: '1997-2006',
  //   flourescence: '',
  //   similar: [],
  //   note: '',
  // },

  {
    id: '',
    Lid: '108',
    Oid: '',
    swatchId: '201100',
    color: '56472F',
    BLName: '',
    LName: 'Earth Yellow',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unreleased',
  },
  {
    id: '',
    Lid: '137',
    Oid: '',
    swatchId: '201600',
    color: 'F48147',
    BLName: '',
    LName: 'Medium Orange',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unreleased',
  },

  {
    id: '',
    Lid: '142',
    Oid: '',
    swatchId: '201700',
    color: 'UNKNWN',
    BLName: '',
    LName: 'Earth Violet',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unkown',
  },
  {
    id: '',
    Lid: '152',
    Oid: '',
    swatchId: '201800',
    color: 'UNKNWN',
    BLName: '',
    LName: 'Earth Red',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unknown',
  },
  {
    id: '',
    Lid: '159',
    Oid: '',
    swatchId: '202100',
    color: 'UNKNWN',
    BLName: '',
    LName: 'Medium Reddish-Orange',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unkown',
  },
  {
    id: '',
    Lid: '168',
    Oid: '',
    swatchId: '202200',
    color: '60564C',
    BLName: '',
    LName: 'Gun Metallic',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Pearl',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unknown',
  },
  {
    id: '',
    Lid: '193',
    Oid: '',
    swatchId: '203100',
    color: 'EC441D',
    BLName: '',
    LName: 'Flame Reddish Orange',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unknown',
  },
  {
    id: '',
    Lid: '209',
    Oid: '',
    swatchId: '203300',
    color: 'A47624',
    BLName: '',
    LName: 'Dark Curry',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unknown',
  },
  {
    id: '',
    Lid: '211',
    Oid: '',
    swatchId: '203500',
    color: '3FB6A9',
    BLName: '',
    LName: 'Turquoise',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unknown',
  },
  {
    id: '',
    Lid: '223',
    Oid: '',
    swatchId: '203700',
    color: 'F17880',
    BLName: '',
    LName: 'Light Pink',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Solid',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unreleased',
  },
  {
    id: '',
    Lid: '228',
    Oid: '',
    swatchId: '204000',
    color: '55A5AF',
    BLName: '',
    LName: 'Transparent Medium Bluish Green',
    OName: '',
    parts: '0',
    inSets: '0',
    type: 'Transparent',
    colorTimeline: ' - ',
    flourescence: '',
    similar: [],
    note: 'Unknown',
  },
  // {
  //   id: "",
  //   Lid: "301",
  //Oid: '',//
  //swatchId: "2046",
  //   color: "fff",
  //   BLName: "",
  //   LName: "Silver",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Pearl",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },

  // {
  //   id: "",
  //   Lid: "331",
  //Oid: '',//
  //swatchId: "2048",
  //   color: "EEEEEE",
  //   BLName: "",
  //   LName: "Lacquer",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Ink",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "Slightly bluish-white",
  // },

  // {
  //   id: "",
  //   Lid: "332",
  //Oid: '',//
  //swatchId: "2049",
  //   color: "D06D4F",
  //   BLName: "",
  //   LName: "Fluorescent Red Ink",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Ink",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },

  // {
  //   id: "",
  //   Lid: "333",
  //Oid: '',//
  //swatchId: "2050",
  //   color: "DBEA7A",
  //   BLName: "",
  //   LName: "Fluorescent Green Ink",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Ink",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },

  // {
  //   id: "",
  //   Lid: "334",
  //Oid: '',//
  //swatchId: "2051",
  //   color: "764D3B",
  //   BLName: "",
  //   LName: "Copper Ink",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Ink",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },

  // {
  //   id: "",
  //   Lid: "337",
  //Oid: '',//
  //swatchId: "2052",
  //   color: "3E3C39",
  //   BLName: "",
  //   LName: "Titanium",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Ink",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },
  // {
  //   id: "",
  //   Lid: "344",
  //Oid: '',//
  //swatchId: "2056",
  //   color: "fff",
  //   BLName: "",
  //   LName: "Cyan Metallic Ink",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Ink",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },

  // {
  //   id: "",
  //   Lid: "345",
  //Oid: '',//
  //swatchId: "2057",
  //   color: "fff",
  //   BLName: "",
  //   LName: "Magenta Metallic Ink",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Ink",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },
  // {
  //   id: "",
  //   Lid: "357",
  //Oid: '',//
  //swatchId: "2065",
  //   color: "fff",
  //   BLName: "",
  //   LName: "Rainbow Shimmer Ink",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Ink",
  //   colorTimeline: "2019- ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },
  // {
  //   id: "",
  //   Lid: "429",
  //Oid: '',//
  //swatchId: "2070",
  //   color: "F2DE2A",
  //   BLName: "",
  //   LName: "Yellow",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Process",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },

  // {
  //   id: "",
  //   Lid: "439",
  //Oid: '',//
  //swatchId: "2071",
  //   color: "C20084",
  //   BLName: "",
  //   LName: "Magenta",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Process",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },

  // {
  //   id: "",
  //   Lid: "454",
  //Oid: '',//
  //swatchId: "2072",
  //   color: "3797CD",
  //   BLName: "",
  //   LName: "Cyan",
  //   OName: "",
  //   parts: "0",
  //   inSets: "0",
  //   type: "Process",
  //   colorTimeline: " - ",
  //   flourescence: "",
  //   similar: [],
  //   note: "",
  // },
];
let a13 = unreleased.map((color) => ({ ...color, type: 'unreleased' }));

export const colors = [
  ...a1,
  ...a2,
  ...a3,
  ...a4,
  ...a5,
  ...a6,
  ...a7,
  ...a8,
  ...a9,
  ...a10,
  ...a11,
  ...a12,
  ...a13,
];
